SET IDENTITY_INSERT [dbo].[Customers] ON
INSERT INTO [dbo].[Customers] ([Id], [ImgPath], [FirstName], [SecondName], [MiddleName], [Email], [RegisteredDate], [BirthDate], [IsSubscribedToNewsletter], [MembershipTypeId]) VALUES (1, N'/Content/Images/WEB_square.jpg', N'Terserta', N'Fertino', N'Andreas', N'terserad@hotmail.com', N'2010-03-17 00:00:00', N'1986-07-21 00:00:00', 1, 3)
INSERT INTO [dbo].[Customers] ([Id], [ImgPath], [FirstName], [SecondName], [MiddleName], [Email], [RegisteredDate], [BirthDate], [IsSubscribedToNewsletter], [MembershipTypeId]) VALUES (2, N'/Content/Images/elam_portrait.jpg', N'Elam', N'Bonaventure', N'Schuchardt', N'schuchardt@gmail.com', N'2008-05-29 00:00:00', N'1990-03-15 00:00:00', 0, 3)
INSERT INTO [dbo].[Customers] ([Id], [ImgPath], [FirstName], [SecondName], [MiddleName], [Email], [RegisteredDate], [BirthDate], [IsSubscribedToNewsletter], [MembershipTypeId]) VALUES (3, N'/Content/Images/hesiodos_portrait.jpg', N'Hesiodos', N'Essen', N'Hildimar', N'hildimar@gmail.com', N'2007-01-29 00:00:00', N'1976-09-18 00:00:00', 1, 4)
INSERT INTO [dbo].[Customers] ([Id], [ImgPath], [FirstName], [SecondName], [MiddleName], [Email], [RegisteredDate], [BirthDate], [IsSubscribedToNewsletter], [MembershipTypeId]) VALUES (4, N'/Content/Images/Heckman-Darrell-square-e1503328318323.jpg', N'Othmar', N'Sniders', N'Winthrop', N'sniders@gmail.com', N'2005-10-11 00:00:00', N'1999-11-15 00:00:00', 0, 2)
INSERT INTO [dbo].[Customers] ([Id], [ImgPath], [FirstName], [SecondName], [MiddleName], [Email], [RegisteredDate], [BirthDate], [IsSubscribedToNewsletter], [MembershipTypeId]) VALUES (5, N'/Content/Images/lilia_portrait.jpg', N'Lilia', N'Jewel', N'Diana', N'jeweldiana@gmail.com', N'2008-09-21 00:00:00', N'1989-06-15 00:00:00', 1, 1)
INSERT INTO [dbo].[Customers] ([Id], [ImgPath], [FirstName], [SecondName], [MiddleName], [Email], [RegisteredDate], [BirthDate], [IsSubscribedToNewsletter], [MembershipTypeId]) VALUES (6, N'/Content/Images/terserta_portrait.jpg', N'Marcel', N'Matylda', N'Krusen', N'matkrusen@gmail.com', N'2004-12-29 00:00:00', N'2001-05-15 00:00:00', 1, 4)
INSERT INTO [dbo].[Customers] ([Id], [ImgPath], [FirstName], [SecondName], [MiddleName], [Email], [RegisteredDate], [BirthDate], [IsSubscribedToNewsletter], [MembershipTypeId]) VALUES (7, N'/Content/Images/square.jpg', N'Olga', N'Razumovskaya', N'Andreevna', N'kitty@meta.ua', N'2009-07-30 00:00:00', N'2000-01-13 00:00:00', 0, 1)
SET IDENTITY_INSERT [dbo].[Customers] OFF
